eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@10.143.253.56:7011/eureka  #注册 中心已经开启认证
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    non-secure-port: ${server.port} #被调用的单元服务需要指定服务端口
spring:
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.100.130.128:3306/alan-oauth?useUnicode=true&amp;\
           characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver